-- One server, many possible rooms. v0.6 enables only the general conversation.
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR(24) NOT NULL,
  username_key VARCHAR(24) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT username_key_lower CHECK (username_key = lower(username))
);

CREATE TABLE IF NOT EXISTS invites (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username_key VARCHAR(24) NOT NULL,
  token_hash BYTEA NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  used_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS invites_unused_idx ON invites(username_key) WHERE used_at IS NULL;

CREATE TABLE IF NOT EXISTS sessions (
  token_hash BYTEA PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_expiration_idx ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('general', 'direct', 'group')),
  name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO conversations (id,kind,name) VALUES (1,'general','General') ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('conversations','id'), (SELECT max(id) FROM conversations));

CREATE TABLE IF NOT EXISTS conversation_members (
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (conversation_id,user_id)
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  legacy_username VARCHAR(24),
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT valid_message_length CHECK (octet_length(body) BETWEEN 1 AND 2048),
  CONSTRAINT message_has_sender CHECK (sender_id IS NOT NULL OR legacy_username IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS messages_conversation_id_idx ON messages(conversation_id,id);
